# Generated by Django 3.1 on 2020-08-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Websote',
            new_name='Website',
        ),
    ]
